package com.wq.miaosha.mapper;

import com.wq.miaosha.entity.MiaoshaGoods;

public interface MiaoshaGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MiaoshaGoods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MiaoshaGoods
     *
     * @mbg.generated
     */
    int insert(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MiaoshaGoods
     *
     * @mbg.generated
     */
    int insertSelective(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MiaoshaGoods
     *
     * @mbg.generated
     */
    MiaoshaGoods selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MiaoshaGoods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MiaoshaGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MiaoshaGoods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MiaoshaGoods record);
}