package com.wq.miaosha.entity;

import java.io.Serializable;
import java.util.Date;

public class MiaoshaGoods implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MiaoshaGoods.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MiaoshaGoods.goods_Id
     *
     * @mbg.generated
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MiaoshaGoods.stock_Count
     *
     * @mbg.generated
     */
    private Integer stockCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MiaoshaGoods.start_Date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MiaoshaGoods.end_Date
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MiaoshaGoods.miaosha_price
     *
     * @mbg.generated
     */
    private Double miaoshaPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MiaoshaGoods
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MiaoshaGoods.id
     *
     * @return the value of MiaoshaGoods.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MiaoshaGoods.id
     *
     * @param id the value for MiaoshaGoods.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MiaoshaGoods.goods_Id
     *
     * @return the value of MiaoshaGoods.goods_Id
     *
     * @mbg.generated
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MiaoshaGoods.goods_Id
     *
     * @param goodsId the value for MiaoshaGoods.goods_Id
     *
     * @mbg.generated
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MiaoshaGoods.stock_Count
     *
     * @return the value of MiaoshaGoods.stock_Count
     *
     * @mbg.generated
     */
    public Integer getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MiaoshaGoods.stock_Count
     *
     * @param stockCount the value for MiaoshaGoods.stock_Count
     *
     * @mbg.generated
     */
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MiaoshaGoods.start_Date
     *
     * @return the value of MiaoshaGoods.start_Date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MiaoshaGoods.start_Date
     *
     * @param startDate the value for MiaoshaGoods.start_Date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MiaoshaGoods.end_Date
     *
     * @return the value of MiaoshaGoods.end_Date
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MiaoshaGoods.end_Date
     *
     * @param endDate the value for MiaoshaGoods.end_Date
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MiaoshaGoods.miaosha_price
     *
     * @return the value of MiaoshaGoods.miaosha_price
     *
     * @mbg.generated
     */
    public Double getMiaoshaPrice() {
        return miaoshaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MiaoshaGoods.miaosha_price
     *
     * @param miaoshaPrice the value for MiaoshaGoods.miaosha_price
     *
     * @mbg.generated
     */
    public void setMiaoshaPrice(Double miaoshaPrice) {
        this.miaoshaPrice = miaoshaPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MiaoshaGoods
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", stockCount=").append(stockCount);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", miaoshaPrice=").append(miaoshaPrice);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}