package com.wq.miaosha.entity;

import java.io.Serializable;
import java.util.Date;

public class OrderInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.user_id
     *
     * @mbg.generated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.goods_id
     *
     * @mbg.generated
     */
    private Long goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.delivery_addr_id
     *
     * @mbg.generated
     */
    private Long deliveryAddrId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.goods_name
     *
     * @mbg.generated
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.goods_count
     *
     * @mbg.generated
     */
    private Integer goodsCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.goods_price
     *
     * @mbg.generated
     */
    private Double goodsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orderinfo.pay_date
     *
     * @mbg.generated
     */
    private Date payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.id
     *
     * @return the value of orderinfo.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.id
     *
     * @param id the value for orderinfo.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.user_id
     *
     * @return the value of orderinfo.user_id
     *
     * @mbg.generated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.user_id
     *
     * @param userId the value for orderinfo.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.goods_id
     *
     * @return the value of orderinfo.goods_id
     *
     * @mbg.generated
     */
    public Long getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.goods_id
     *
     * @param goodsId the value for orderinfo.goods_id
     *
     * @mbg.generated
     */
    public void setGoodsId(Long goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.delivery_addr_id
     *
     * @return the value of orderinfo.delivery_addr_id
     *
     * @mbg.generated
     */
    public Long getDeliveryAddrId() {
        return deliveryAddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.delivery_addr_id
     *
     * @param deliveryAddrId the value for orderinfo.delivery_addr_id
     *
     * @mbg.generated
     */
    public void setDeliveryAddrId(Long deliveryAddrId) {
        this.deliveryAddrId = deliveryAddrId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.goods_name
     *
     * @return the value of orderinfo.goods_name
     *
     * @mbg.generated
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.goods_name
     *
     * @param goodsName the value for orderinfo.goods_name
     *
     * @mbg.generated
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.goods_count
     *
     * @return the value of orderinfo.goods_count
     *
     * @mbg.generated
     */
    public Integer getGoodsCount() {
        return goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.goods_count
     *
     * @param goodsCount the value for orderinfo.goods_count
     *
     * @mbg.generated
     */
    public void setGoodsCount(Integer goodsCount) {
        this.goodsCount = goodsCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.goods_price
     *
     * @return the value of orderinfo.goods_price
     *
     * @mbg.generated
     */
    public Double getGoodsPrice() {
        return goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.goods_price
     *
     * @param goodsPrice the value for orderinfo.goods_price
     *
     * @mbg.generated
     */
    public void setGoodsPrice(Double goodsPrice) {
        this.goodsPrice = goodsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.status
     *
     * @return the value of orderinfo.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.status
     *
     * @param status the value for orderinfo.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.create_date
     *
     * @return the value of orderinfo.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.create_date
     *
     * @param createDate the value for orderinfo.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orderinfo.pay_date
     *
     * @return the value of orderinfo.pay_date
     *
     * @mbg.generated
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orderinfo.pay_date
     *
     * @param payDate the value for orderinfo.pay_date
     *
     * @mbg.generated
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderinfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", goodsId=").append(goodsId);
        sb.append(", deliveryAddrId=").append(deliveryAddrId);
        sb.append(", goodsName=").append(goodsName);
        sb.append(", goodsCount=").append(goodsCount);
        sb.append(", goodsPrice=").append(goodsPrice);
        sb.append(", status=").append(status);
        sb.append(", createDate=").append(createDate);
        sb.append(", payDate=").append(payDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}